server:
  port: 7006
spring:
  application:
    name: eureka-provider
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    hostname: localhost
