server :
 port : 8835
spring :
  application :
      name : gateway-zuul

eureka :
  client :
    service-url:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    eureka-consumer:
      path: /eureka-hystrix-client/**
      serviceId: eureka-hystrix-client
  ribbon:
    eager-load:
      enabled: true




